<?php require_once __DIR__.'/config.php'; $it=atlas_lang()==='it'; ?>
<!doctype html><html lang="<?php echo atlas_h(atlas_lang()); ?>"><head><title><?php echo $it?'Documentazione LJSF 3':'LJSF 3 Documentation'; ?></title><?php require __DIR__.'/css/page_header.php'; page_header('.'); ?></head><body>
<div id="main"><div id="header"><?php require __DIR__.'/css/main_header.php'; main_header($LJSFi_VO,'.'); require __DIR__.'/css/menubar.php'; menubar('.'); ?></div>
<div id="site_content"><div id="content" style="width:100%;float:none" class="atlas-docs">
<h1><?php echo $it?'LJSF 3 — Manuale applicativo':'LJSF 3 — Application Guide'; ?></h1>
<p><?php echo $it?'LJSF 3 è il sistema ATLAS per la gestione del deployment software, delle release, dei siti, delle richieste di installazione, dei target e dei task operativi. Questa documentazione descrive il comportamento corrente dell’applicazione.':'LJSF 3 is the ATLAS system for software deployment management, releases, sites, installation requests, targets and operational tasks. This documentation describes the current application behavior.'; ?></p>
<nav class="atlas-doc-index">
<a href="#access"><?php echo $it?'Accesso e ruoli':'Access and roles'; ?></a><a href="#navigation"><?php echo $it?'Navigazione':'Navigation'; ?></a><a href="#data"><?php echo $it?'Release, siti e task':'Releases, sites and tasks'; ?></a><a href="#charts"><?php echo $it?'Grafici e report':'Charts and reports'; ?></a><a href="#database">Database</a><a href="#kubernetes">Kubernetes</a><a href="#api">REST API</a><a href="#security"><?php echo $it?'Sicurezza':'Security'; ?></a><a href="#troubleshooting">Troubleshooting</a>
</nav>
<section id="access"><h2><?php echo $it?'Accesso, autenticazione e ruoli':'Access, authentication and roles'; ?></h2><p><?php echo $it?'Le funzioni pubbliche sono consultabili senza autenticazione. Le funzioni protette richiedono un certificato client valido con ruolo associato oppure un account locale abilitato. L’account locale iniziale è admin con ruolo master; al primo accesso può essere richiesto il cambio password e l’attivazione TOTP.':'Public functions are available without authentication. Protected functions require a valid client certificate with an associated role or an enabled local account. The initial local account is admin with the master role; first login may require password change and TOTP enrollment.'; ?></p><p><a href="auth/login.php"><?php echo atlas_h(atlas_t('go_login')); ?></a></p></section>
<section id="navigation"><h2><?php echo $it?'Navigazione e interfaccia mobile':'Navigation and mobile interface'; ?></h2><p><?php echo $it?'Su desktop il menu è orizzontale. Su smartphone è un pannello verticale a destra, chiuso per default, con sezioni espandibili e una voce per riga. La lingua viene scelta dal browser (italiano per browser italiani, inglese negli altri casi) e può essere cambiata con il selettore in alto a destra.':'On desktop the navigation is horizontal. On mobile it is a right-side vertical drawer, collapsed by default, with expandable sections and one item per row. Language follows the browser (Italian for Italian browsers, English otherwise) and can be changed with the top-right selector.'; ?></p><p><?php echo $it?'Le tabelle grandi mostrano 200 record per default, con selettore 50/100/200/500/1000/Tutti. La paginazione è applicata solo alla visualizzazione browser; API e script non vengono limitati. Su mobile le tabelle larghe vengono convertite in record compatti: mostrano per default solo i campi principali e possono essere espanse riga per riga per vedere tutti i dettagli, evitando ove possibile lo scorrimento orizzontale.':'Large tables show 200 records by default with a 50/100/200/500/1000/All selector. Pagination applies only to browser rendering; APIs and scripts are not limited. On mobile, wide tables are converted to compact records: primary fields are shown by default and each row can be expanded to reveal all details, avoiding horizontal scrolling whenever possible.'; ?></p></section>
<section id="data"><h2><?php echo $it?'Release, siti, architetture, target e task':'Releases, sites, architectures, targets and tasks'; ?></h2><p><?php echo $it?'Le sezioni di gestione consentono di definire, modificare e consultare release, architetture, InfoSys, siti, target e task. Le operazioni di modifica sono protette dai ruoli applicativi. Le richieste di installazione e i riepiloghi permettono di seguire lo stato del deployment sui siti.':'Management sections define, update and inspect releases, architectures, InfoSys entries, sites, targets and tasks. Modification actions are protected by application roles. Installation requests and summaries track deployment status across sites.'; ?></p></section>
<section id="charts"><h2><?php echo $it?'Grafici, summary e report':'Charts, summaries and reports'; ?></h2><p><?php echo $it?'I grafici vengono creati localmente on demand in SVG/HTML. Non vengono usati Google Charts o altri servizi esterni per renderizzare i grafici. I CronJob di manutenzione producono soltanto summary/cache dei dati storici; la UI legge questi summary e genera il grafico al momento della richiesta.':'Charts are rendered locally on demand as SVG/HTML. Google Charts and other external chart-rendering services are not used. Maintenance CronJobs only produce historical summaries/cache data; the UI reads the summaries and renders charts when requested.'; ?></p></section>
<section id="database"><h2>Database</h2><p><?php echo $it?'L’applicazione usa endpoint RW, RO e broker configurati nel bootstrap Secret. TLS è opzionale e può essere reso obbligatorio dal wizard. Se il database applicativo non esiste e ATLAS_DB_AUTO_INIT è attivo, il bootstrap tenta di creare lo schema standard. Le tabelle di autenticazione locale vengono create automaticamente quando mancanti usando la credenziale bootstrap temporanea configurata dal wizard.':'The application uses RW, RO and broker endpoints configured in the bootstrap Secret. TLS is optional and can be enforced by the wizard. If the application database does not exist and ATLAS_DB_AUTO_INIT is enabled, bootstrap attempts to create the default schema. Missing local-authentication tables are created automatically using the temporary bootstrap credential configured by the wizard.'; ?></p></section>
<section id="kubernetes"><h2>Kubernetes</h2><p><?php echo $it?'Il Deployment monta configurazione, certificati TLS e storage persistente. Con PVC ReadWriteOnce, i job di manutenzione vengono co-locati sul nodo del server. L’Ingress HAProxy usa sia spec.ingressClassName: haproxy sia l’annotazione kubernetes.io/ingress.class: haproxy. Il wizard si auto-aggiorna e si riavvia automaticamente quando installa una revisione più recente.':'The Deployment mounts configuration, TLS certificates and persistent storage. With a ReadWriteOnce PVC, maintenance jobs are co-located on the server node. HAProxy Ingress uses both spec.ingressClassName: haproxy and kubernetes.io/ingress.class: haproxy. The wizard self-updates and re-executes automatically when it installs a newer revision.'; ?></p></section>
<section id="api"><h2>REST API</h2><p><?php echo $it?'Le API REST v1 affiancano gli endpoint legacy e offrono risorse JSON versionate per release, siti, richieste, task, architetture, target e utenti. Usano metodi HTTP standard, paginazione, filtri, status code coerenti e autenticazione tramite certificato client, sessione locale o HTTP Basic.':'REST API v1 runs alongside legacy endpoints and exposes versioned JSON resources for releases, sites, requests, tasks, architectures, targets and users. It uses standard HTTP methods, pagination, filters, consistent status codes, and authentication through client certificates, local sessions, or HTTP Basic.'; ?></p><p><a href="/atlas_install/api/v1/">/atlas_install/api/v1/</a></p></section>
<section id="security"><h2><?php echo $it?'Sicurezza':'Security'; ?></h2><p><?php echo $it?'Le connessioni DB possono usare TLS; le pagine protette applicano autenticazione e ruoli; le richieste state-changing sono sottoposte ai controlli same-origin/CSRF previsti. Le password, i token TOTP e le chiavi non vengono scritti nei log applicativi.':'Database connections can use TLS; protected pages enforce authentication and roles; state-changing requests are subject to same-origin/CSRF controls. Passwords, TOTP tokens and keys are not written to application logs.'; ?></p></section>
<section id="troubleshooting"><h2>Troubleshooting</h2><p><?php echo $it?'Gli eventi di startup sono visibili con kubectl logs e mostrano sincronizzazione configurazione, bootstrap DB, controllo TLS, run iniziale IGTF/fetch-crl, PHP-FPM e Apache. Gli errori applicativi sono marcati [ATLAS_APP], quelli di bootstrap DB [atlas-db-bootstrap].':'Startup events are visible in kubectl logs and show configuration sync, DB bootstrap, TLS validation, initial IGTF/fetch-crl run, PHP-FPM and Apache startup. Application errors use the [ATLAS_APP] prefix and DB bootstrap messages use [atlas-db-bootstrap].'; ?></p></section>
</div></div><?php echo atlas_identity_details_html(); ?><div id="footer"><p>LJSF 3 · ATLAS Installation System</p></div></div></body></html>
