<?php
require_once __DIR__.'/../config.php'; atlas_require_authenticated(); atlas_require_master(); atlas_local_auth_schema(); $db=atlas_local_db();$error='';$message='';$newTotpUri='';$newTotpSecret='';
if(session_status()!==PHP_SESSION_ACTIVE){session_name('ATLASADM');session_start(['cookie_secure'=>true,'cookie_httponly'=>true,'cookie_samesite'=>'Strict']);}if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
if($_SERVER['REQUEST_METHOD']==='POST'){try{if(!hash_equals((string)$_SESSION['csrf'],(string)($_POST['csrf']??'')))throw new RuntimeException('CSRF non valido');$action=(string)$_POST['action'];$id=(int)($_POST['id']??0);
if($action==='create'){ $u=trim((string)$_POST['username']); if(!preg_match('/^[A-Za-z0-9._-]{1,64}$/D',$u))throw new RuntimeException('Username non valido');$fn=trim((string)$_POST['first_name']);$ln=trim((string)$_POST['last_name']);$em=trim((string)$_POST['email']);$role=(string)$_POST['role'];if(!in_array($role,['user','admin','master'],true))throw new RuntimeException('Ruolo non valido');$pw=(string)$_POST['password'];if(strlen($pw)<12)throw new RuntimeException('Password iniziale: almeno 12 caratteri');$h=password_hash($pw,PASSWORD_DEFAULT);$st=$db->prepare('INSERT INTO atlas_local_user(username,first_name,last_name,email,role,enabled,password_hash,must_change_password) VALUES(?,?,?,?,?,1,?,1)');$st->bind_param('ssssss',$u,$fn,$ln,$em,$role,$h);$st->execute();$message='Utente creato';atlas_auth_log('local_user_created',['target'=>$u]); }
elseif($action==='update'){ $fn=trim((string)$_POST['first_name']);$ln=trim((string)$_POST['last_name']);$em=trim((string)$_POST['email']);$role=(string)$_POST['role'];$en=isset($_POST['enabled'])?1:0;$st=$db->prepare('UPDATE atlas_local_user SET first_name=?,last_name=?,email=?,role=?,enabled=? WHERE id=?');$st->bind_param('ssssii',$fn,$ln,$em,$role,$en,$id);$st->execute();$message='Utente aggiornato';atlas_auth_log('local_user_updated',['target_id'=>$id]); }
elseif($action==='delete_user'){ $me=atlas_current_identity(); if(($me['source']??'')==='local' && (int)($me['id']??0)===$id) throw new RuntimeException('Non puoi cancellare il tuo account mentre lo stai usando.'); $st=$db->prepare('SELECT role,enabled,username FROM atlas_local_user WHERE id=?');$st->bind_param('i',$id);$st->execute();$target=$st->get_result()->fetch_assoc();if(!$target)throw new RuntimeException('Utente non trovato.');if($target['role']==='master'&&(int)$target['enabled']===1){$cnt=(int)($db->query("SELECT COUNT(*) c FROM atlas_local_user WHERE role='master' AND enabled=1")->fetch_assoc()['c']??0);if($cnt<=1)throw new RuntimeException('Non puoi cancellare l’ultimo master attivo.');}$st=$db->prepare('DELETE FROM atlas_local_user WHERE id=?');$st->bind_param('i',$id);$st->execute();$message='Utente cancellato';atlas_auth_log('local_user_deleted',['target'=>(string)$target['username']]); }
elseif($action==='reset_password'){ $pw=(string)$_POST['password'];if(strlen($pw)<12)throw new RuntimeException('Password: almeno 12 caratteri');$h=password_hash($pw,PASSWORD_DEFAULT);$st=$db->prepare('UPDATE atlas_local_user SET password_hash=?,must_change_password=1 WHERE id=?');$st->bind_param('si',$h,$id);$st->execute();$db->query('DELETE FROM atlas_local_session WHERE user_id='.$id);$message='Password resettata; cambio obbligatorio al prossimo login';atlas_auth_log('local_password_reset',['target_id'=>$id]); }
elseif($action==='delete_totp'){ $tid=(int)$_POST['totp_id'];$st=$db->prepare('DELETE FROM atlas_local_totp WHERE id=? AND user_id=?');$st->bind_param('ii',$tid,$id);$st->execute();$message='TOTP eliminato';atlas_auth_log('totp_deleted',['target_id'=>$id,'totp_id'=>$tid]); }
elseif($action==='toggle_totp'){ $tid=(int)$_POST['totp_id'];$st=$db->prepare('UPDATE atlas_local_totp SET enabled=1-enabled WHERE id=? AND user_id=?');$st->bind_param('ii',$tid,$id);$st->execute();$message='Stato TOTP modificato';atlas_auth_log('totp_toggled',['target_id'=>$id,'totp_id'=>$tid]); }
elseif($action==='add_totp'){ $label=trim((string)$_POST['label']);$secret=atlas_totp_generate_secret();$enc=atlas_secret_encrypt($secret);$st=$db->prepare('INSERT INTO atlas_local_totp(user_id,label,secret_enc,enabled) VALUES(?,?,?,1)');$st->bind_param('iss',$id,$label,$enc);$st->execute();$ur=$db->query('SELECT username FROM atlas_local_user WHERE id='.(int)$id)->fetch_assoc();$newTotpSecret=$secret;$newTotpUri=atlas_totp_uri((string)($ur['username']??('user-'.$id)),$secret);$message='TOTP aggiunto. Registra ora il nuovo autenticatore.';atlas_auth_log('totp_added',['target_id'=>$id]); }
elseif($action==='session_hours'){ $h=max(1,min(168,(int)$_POST['hours']));atlas_set_auth_setting('session_hours',(string)$h);$message='Durata sessione aggiornata';atlas_auth_log('session_duration_changed',['hours'=>$h]); }
}catch(Throwable $e){$error=$e->getMessage();atlas_auth_log('master_action_failed',['error'=>$e->getMessage()]);}}
$users=$db->query('SELECT * FROM atlas_local_user ORDER BY username')->fetch_all(MYSQLI_ASSOC);$hours=atlas_auth_setting('session_hours','8');
?><!doctype html><html lang="it"><head><title>Utenti locali</title><?php require __DIR__.'/../css/page_header.php';page_header('..');?></head><body><div id="main"><div id="header"><?php require __DIR__.'/../css/main_header.php';main_header($LJSFi_VO,'..');require __DIR__.'/../css/menubar.php';menubar('..');?></div><div id="site_content"><div id="content" style="width:100%;float:none"><h1>Utenti locali</h1><?php if($error):?><div class="atlas-alert error"><?=atlas_h($error)?></div><?php endif;?><?php if($message):?><div class="atlas-alert success atlas-break"><?=atlas_h($message)?></div><?php endif;?><?php if($newTotpUri!==''): $newQr=atlas_totp_qr_data_uri($newTotpUri); ?><div class="atlas-card atlas-totp-enroll"><?php if($newQr!==''):?><figure class="atlas-totp-qr"><img src="<?=atlas_h($newQr)?>" alt="TOTP QR code"><figcaption>Scansiona il QR code con l’app di autenticazione</figcaption></figure><?php endif;?><div><p><strong>Secret:</strong> <span class="atlas-code"><?=atlas_h($newTotpSecret)?></span></p><p class="atlas-code atlas-break"><?=atlas_h($newTotpUri)?></p></div></div><?php endif;?>
<div class="atlas-card"><h2>Sessioni</h2><form method="post"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="session_hours"><label>Durata sessione locale (ore) <input type="number" name="hours" min="1" max="168" value="<?=atlas_h($hours)?>"></label> <button>Salva</button></form></div>
<div class="atlas-card"><h2>Nuovo utente</h2><form method="post" class="atlas-form"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="create"><div class="atlas-form-grid"><input name="username" placeholder="username" required><input name="first_name" placeholder="nome"><input name="last_name" placeholder="cognome"><input name="email" type="email" placeholder="email"><select name="role"><option>user</option><option>admin</option><option>master</option></select><input name="password" type="password" placeholder="password iniziale (>=12)" required></div><button>Crea</button></form></div>
<?php foreach($users as $u):?><div class="atlas-card"><h2><?=atlas_h($u['username'])?> <small><?= $u['enabled']?'attivo':'disabilitato' ?></small></h2><form method="post" class="atlas-form"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=$u['id']?>"><div class="atlas-form-grid"><input name="first_name" value="<?=atlas_h($u['first_name'])?>" placeholder="nome"><input name="last_name" value="<?=atlas_h($u['last_name'])?>" placeholder="cognome"><input name="email" type="email" value="<?=atlas_h($u['email'])?>" placeholder="email"><select name="role"><?php foreach(['user','admin','master'] as $r):?><option<?=$u['role']===$r?' selected':''?>><?=$r?></option><?php endforeach;?></select><label><input type="checkbox" name="enabled" <?=$u['enabled']?'checked':''?>> abilitato</label></div><button>Salva dati</button></form>
<form method="post" class="atlas-inline"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="password" name="password" placeholder="nuova password" required><button>Reset password</button></form><form method="post" class="atlas-inline" onsubmit="return confirm('Cancellare questo utente locale?');"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="atlas-danger-button">Cancella utente</button></form>
<h3>TOTP</h3><?php $ts=atlas_user_totps((int)$u['id']); if(!$ts):?><p class="atlas-muted">Nessun TOTP.</p><?php endif; foreach($ts as $t):?><div class="atlas-inline"><span><?=atlas_h($t['label'])?> · <?=$t['enabled']?'attivo':'disabilitato'?></span><form method="post"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="hidden" name="totp_id" value="<?=$t['id']?>"><button name="action" value="toggle_totp">Abilita/disabilita</button><button name="action" value="delete_totp">Elimina</button></form></div><?php endforeach;?><form method="post" class="atlas-inline"><input type="hidden" name="csrf" value="<?=atlas_h($_SESSION['csrf'])?>"><input type="hidden" name="action" value="add_totp"><input type="hidden" name="id" value="<?=$u['id']?>"><input name="label" value="Authenticator" required><button>Aggiungi TOTP</button></form></div><?php endforeach;?></div></div></div></body></html>